### ISSUE TITLE
Frontend typescript error

### ISSUE THREAD

**Issue by jistjoalal** [kaviarjs/x-boilerplate#2]
I'm not a typescript guy, but was able to get the API running. However, I'm stuck starting the frontend on this probably embarrassingly simple error.

Something about my Typescript install/config/linter? Thanks for any help, and I better start learning TS because Kaviar looks awesome.

```
Failed to compile

C:/Users/jist/Desktop/code/clones/x-boilerplate/microservices/ui/src/bundles/UIAppBundle/collections/Comments/Comments.collection.ts
TypeScript error in C:/Users/jist/Desktop/code/clones/x-boilerplate/microservices/ui/src/bundles/UIAppBundle/collections/Comments/Comments.collection.ts(4,14):
Non-abstract class 'CommentsCollection' does not implement inherited abstract member 'name' from class 'Collection<Comment>'.  TS2515

    2 | import { Comment } from "./Comment.model";
    3 | 
  > 4 | export class CommentsCollection extends Collection<Comment> {
      |              ^
    5 |   getName() {
    6 |     return "comments";
    7 |   }

This error occurred during the build time and cannot be dismissed.
```

**Comment by theodorDiaconu** [comment]
It may be due to older version of @kaviar/x-ui ?

**Comment by theodorDiaconu** [comment]
Please ensure you're up to date with the latest version. Running `npm update` might solve it.

**Comment by jistjoalal** [comment]
You're right, I don't know why I didn't try that. Thanks again for the demo I'm gonna have fun tinkering with it.
